server:
  port: 8090

eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka/

cloud:
  s3:
    bucket: com.paranmanzang.chat
    access-key: AKIAQXPZDAMK3DSXSQTL
    access-secret-key: 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

spring:
  application:
    name: file-service
  profiles:
    active: local
    config:
      import: optional:configserver:http://localhost:8888
  management:
    endpoints:
      web:
        exposure:
          include: health,info

  datasource:
    url: jdbc:mysql://127.0.0.1:3306/parandb
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver

  data:
    mongodb:
      uri: mongodb://root:1234@127.0.0.1:27017/parandb?authSource=admin
    cache:
      type: redis
