server:
  port: 8090

ncp:
  storage:
    accessKey: ncp_iam_BPASKR5v1Hekg1oSwboI
    secretKey: ncp_iam_BPKSKRLeX8QfYjS5RaANbRaO6Q2XThf0aR
    region: kr-standard
    endpoint: https://kr.object.ncloudstorage.com


eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka/

spring:
  application:
    name: file-service
  profiles:
    active: local
    config:
      import: optional:configserver:http://localhost:8888
  management:
    endpoints:
      web:
        exposure:
          include: health,info

  datasource:
    url: jdbc:mysql://127.0.0.1:3306/parandb
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver

  data:
    mongodb:
      uri: mongodb://root:1234@127.0.0.1:27017/parandb?authSource=admin
    cache:
      type: redis
