server:
  port: 9001
spring:
  application:
    name: comment-service
  profiles:
    active: local
    config:
      import: optional:configserver:http://localhost:8888

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
