server:
  port: 8083

naver:
  client-id: Hlz9JqBuVxtAsSSKyWHw
  client-secret-key: UamL61rm7F

eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka/


spring:
  application:
    name: room-service
  profiles:
    active: local
    config:
      import: optional:configserver:http://localhost:8888
  management:
    endpoints:
      web:
        exposure:
          include: health,info

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect