spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/parandb  # MySQL 데이터베이스 URL
    username: root                             # MySQL 사용자 이름
    password: 1234                             # MySQL 비밀번호
    driver-class-name: com.mysql.cj.jdbc.Driver # MySQL 드라이버 클래스
  application:
    name: room-service
  profiles:
    active: local
    config:
      import: optional:configserver:http://localhost:8888

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
    register-with-eureka: true
    fetch-registry: true

  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
    hostname: localhost


