server:
  port: 8085

spring:
  application:
    name: group-service
  profiles:
    active: local
    config:
      import: optional:configserver:http://localhost:8888


  datasource:
    url: jdbc:mysql://127.0.0.1:3306/parandb  # MySQL 데이터베이스 URL
    username: root                             # MySQL 사용자 이름
    password: 1234                             # MySQL 비밀번호
    driver-class-name: com.mysql.cj.jdbc.Driver # MySQL 드라이버 클래스

    jpa:
      hibernate:
        ddl-auto: update                         # Hibernate DDL 자동 업데이트 설정
      show-sql: true                             # SQL 쿼리 출력 활성화
      properties:
        hibernate:
          dialect: org.hibernate.dialect.MySQLDialect

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
    hostname: localhost