spring:
  application:
    name: group-service  # 서비스 이름, Eureka에 등록될 이름

  cloud:
    config:
      import: optional:configserver:http://localhost:8888  # Config Server가 있을 경우 사용하는 설정, 없다면 optional로 무시됨

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka  # Eureka 서버 주소, 이 주소로 Eureka에 등록됨
    register-with-eureka: true  # Eureka 서버에 서비스 등록
    fetch-registry: true        # Eureka에서 레지스트리 정보 가져오기

  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
    hostname: localhost

server:
  port: 8084
