spring:
  application:
    name: eureka
  config:
    import: optional:configserver:http://211.188.50.31:8888

server:
  port: 8761

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    serviceUrl:
      defaultZone: http://211.188.50.31:8761/eureka
