server:
  port: 8000

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
    register-with-eureka: true
    fetch-registry: true


spring:
  config:
    activate:
      on-profile: default

  application:
    name: api

  main:
    allow-bean-definition-overriding: true
    web-application-type: reactive

  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials RETAIN_UNIQUE
      routes:
        - id: chat-service
          uri: lb://chat-service
          predicates:
            - Path=/api/chats/**
          filters:
            - RemoveRequestHeader=Cookie
            - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin RETAIN_UNIQUE
            - RemoveResponseHeader=Access-Control-Allow-Origin

        - id: comment-service
          uri: lb://comment-service
          predicates:
            - Path=/api/comments/**
            - Method=GET,POST,PUT,DELETE
          filters:
            - RemoveRequestHeader=Cookie

        - id: file-service
          uri: lb://file-service
          predicates:
            - Path=/api/files/**
            - Method=GET,POST,PUT,DELETE
          filters:
            - RemoveRequestHeader=Cookie

        - id: group-service
          uri: lb://group-service
          predicates:
            - Path=/api/groups/**
            - Method=GET,POST,PUT,DELETE
          filters:
            - RemoveRequestHeader=Cookie

        - id: room-service
          uri: lb://room-service
          predicates:
            - Path=/api/rooms/**
            - Method=GET,POST,PUT,DELETE
          filters:
            - RemoveRequestHeader=Cookie

        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/api/users/**
            - Method=GET,POST,PUT,DELETE
          filters:
            - RemoveRequestHeader=Cookie

  jwt:
    issuer: paranmanzang.com
    secret: 80d0f49aacda55f952ff27acda9974f057378ae16a528b0ac35593652b1983b7
    expired:
      access: 600000
      refresh: 1200000

  management:
    endpoints:
      web:
        exposure:
          include: "*" # 모든 엔드포인트 노출
    endpoint:
      shutdown:
        enabled: true
      info:
        enabled: true
      health:
        enabled: true
      beans:
        enabled: true
      httptrace:
        enabled: true
    health:
      circuitbreakers:
        enabled: true # Circuit Breaker 상태를 확인

  resilience4j:
    circuitbreaker:
      configs:
        default:
          slidingWindowType: COUNT_BASED
          slidingWindowSize: 10
          failureRateThreshold: 50
          permittedNumberOfCallsInHalfOpenState: 5
          registerHealthIndicator: true

  profiles:
#    active: local
    config:
      import: optional:configserver:http://localhost:8888

logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.web.cors: DEBUG


