spring:
  application:
    name: chat-service
  profiles:
    active: local
    config:
      import: optional:configserver:http://localhost:8888

  data:
    redis:
      host: localhost
      port: 6379
      username: default
      password: password



    mongodb:
      uri: mongodb://root:1234@127.0.0.1:27017/parandb?authSource=admin
    cache:
      type: redis

server:
  port: 8081